### ISSUE TITLE
Execution against Firefox browser

### ISSUE THREAD

**Issue by VinothMessi** [testproject-io/java-opensdk#65]
**Executed 4 test cases against Firefox and below is my console output:**
![image](https://user-images.githubusercontent.com/34208574/103304378-7bbf0780-4a2e-11eb-93f0-3b13380e9151.png)

Also unable to use driver.quite() after each test case, because after 1st test case completed (error thrown saying session id not available)

**Comment by DavidG8168** [comment]
Hi @VinothMessi.

After our conversation in the TestProject chat, seeing as this is happening on the regular Gecko driver as well, the issue is most likely related to the driver itself or Firefox. 

Have you tried adding the following capability to the Firefox options?

`options.addPreference("dom.ipc.processCount", 1);
`

If this does not work, the issue should be submitted in the Gecko driver GitHub repository.

**Comment by VinothMessi** [comment]
Am using JAVA SDK, how to add the desired capabilities? Any sample :)

**Comment by DavidG8168** [comment]
Sure,

```
FirefoxOptions options = new FirefoxOptions();
options.addPreference("dom.ipc.processCount", 1);

FirefoxDriver driver = new FirefoxDriver(options);
```

**Comment by VinothMessi** [comment]
Ok Thanks

Will try and update 🙂

**Comment by DavidG8168** [comment]
Thank you

**Comment by VinothMessi** [comment]
Hi,

Still the same issue with Firefox even after adding the FirefoxOptions

[image: image.png]

Thanks,
Vinoth.M

**Comment by DavidG8168** [comment]
Hi @VinothMessi .

Does the issue reproduce with pure Selenium without the TestProject SDK?

From exploring the Gecko Driver repository, you can try to:

-- Increase the memory of the machine/docker/vm you are running on.
-- Not running headless Firefox.
-- Revert to an older version of Firefox.

If the failure continues using the regular Gecko Driver, please refer to their repository, as this is an open issue there:
https://github.com/mozilla/geckodriver/issues/1559

**Comment by VinothMessi** [comment]
Ok sure 🙂

**Comment by VinothMessi** [comment]
Hi David,

          Can i deploy this test project agent in an GCP machine and access
it using an external IP Address? instead of localhost?

**Comment by DavidG8168** [comment]
Hi,

Coded tests with the SDK, can only be executed on remote agents on the same network as you are on.
https://github.com/testproject-io/java-opensdk#driver-builder

You can however deploy the Agent on the cloud machine and pull then run the code there as part of a CI/CD pipeline.

In addition recorded tests from the platform itself (non-coded tests made with the TestProject recorder) can be executed on remote agents regardless of what network they are on as long as they are registered to the same account as you are.

But more on those two topics you should receive from the TestProject Support team.

**Comment by VinothMessi** [comment]
Same network I understand, am aiming to deploy test project agent inside a
Kubernetes cluster and expose the service, so I can have 3 agents within 3
nodes and execute with different browsers

Is that possible, because companies don't want to keep their tests within
the Test project UI as it can be accessed by any employee with credentials
from anywhere

Thanks,
Vinoth.M

**Comment by DavidG8168** [comment]
It should be possible to deploy an agent on Kubernetes. 

As for the UI, I believe that access permissions can be restricted to certain projects and tests to specific users in the team.

**Comment by vitalybu** [comment]
@VinothMessi, the TestProject Agent is also available as a docker container: https://hub.docker.com/r/testproject/agent
More information is available on the [Docker Hub](https://hub.docker.com/r/testproject/agent) page the TestProject Documentation [website](https://docs.testproject.io/testproject-agents/testproject-agent-in-docker).

**Comment by VinothMessi** [comment]
Any sample help on deploying the agent inside the kubernetes cluster would
be of greater help to me :)

As for the UI, I believe that access permissions can be restricted to
certain projects and tests to specific users in the team.
Can we block access to Test Project outside a specific network?

**Comment by DavidG8168** [comment]
An example for Kubernetes can be using a .yaml file with the `kubectl apply -f <add-on.yaml>` command.

This Kubernetes .yaml file will bring up an agent with a Chrome container and register it to your account, you will need to edit it the API key to the one from the account you'd like to use:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: testproject-data-volume
  name: testproject-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: testproject-browser-data-volume
  name: testproject-browser-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: testproject-agent
  name: testproject-agent
spec:
  selector:
    matchLabels:
      io.kompose.service: testproject-agent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: testproject-agent
    spec:
      containers:
        - env:
            - name: CHROME
              value: "testproject-chrome-service:4444"
            - name: TP_API_KEY
              value: xxxx
          image: testproject/agent:latest
          name: testproject-agent
          resources: {}
          volumeMounts:
            - mountPath: /var/testproject/agent
              name: testproject-data-volume
      restartPolicy: Always
      volumes:
        - name: testproject-data-volume
          persistentVolumeClaim:
            claimName: testproject-data-volume
      initContainers:
        - name: init-chrome-pod
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://testproject-chrome-service:4444/wd/hub" -o /dev/null) -ne 302]; do
                sleep 2;
              done
---
kind: Service
apiVersion: v1
metadata:
  name: testproject-chrome-service
spec:
  ports:
    - port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    io.kompose.service: testproject-chrome

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: testproject-chrome
  name: testproject-chrome
spec:
  selector:
    matchLabels:
      io.kompose.service: testproject-chrome
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: testproject-chrome
    spec:
      containers:
        - image: selenium/standalone-chrome
          name: headless-chrome
          resources: {}
          volumeMounts:
            - mountPath: /dev/shm
              name: chrome-claim0
      restartPolicy: Always
      volumes:
        - name: chrome-claim0
          persistentVolumeClaim:
            claimName: testproject-browser-data-volume
```

![image](https://user-images.githubusercontent.com/45967111/106039379-bbd2e200-60e1-11eb-98b1-dff68fab78ce.png)


As for the UI, currently no, however we it's on our pipeline for this year to allow deploying the entire TestProject platform locally (the cloud web platform that is used for management, currently only the agent can be deployed locally), so that possibility might be added in the future.

Closing the issue as we have strayed from the original topic.

Please contact us at support@testproject.io or our live chat through the platform for additional information and help regarding other topics.
